p4lang/p4lang.github.io

- _config.yml
- _drafts/year-in-review.md
- _pages/drafts.html
This pull request does two things:
1. It adds support for draft blog posts that are published in at [p4.org/blog/drafts](https://p4.org/blog/drafts).
2. It adds a first draft for a year-in-review blog post.
> Draft posts and year in review

- _drafts/year-in-review.md
> 'Year in Review' edits

- _events/2018-06-05-p4-workshop.md
- _events/2018-06-06-p4-developer-day.md
> Add draft developer day page.

- _events/2018-06-05-p4-workshop.md
Reverts p4lang/p4lang.github.io#94
> Revert "Adding a table w/the agenda"

- _events/2018-06-06-p4-developer-day.md
Add directions, instructor names, keynote, panelists.
> Add Developer Day detailed schedule

- _layouts/spec.html
- _pages/specs.html
The PDF is currently hosted in the p4-spec Github pages.
> Add link to P4Runtime v1.0.0 draft

- _events/2018-06-05-p4-workshop.md
I'm not sure if this is linking it the way I'd like it to.  I uploaded the slides to assets and now I'm trying to create a link to the slides on the Workshop web page.  Did I do this correctly?
> Adding Brian O'Connor's slide

- _events/2018-09-24-p4-eu-workshop.md
> Horizontal alignment. Indicate level of sponsorship.

- _events/2018-09-24-p4-eu-workshop.md
@rkeverman , @prem-bfn , Can one of you please review?
> Added Mario to PC

- _data/publications.yml
Added SMPTE Conference Paper "Programmable Data Plane for Professional Media Networking"
> Added SMPTE Conference Paper

- _data/publications.yml
Added DAIET paper (HotNets17) to publications
> Added DAIET paper (HotNets17)

- _data/publications.yml
Dear maintainer of the repository, 
I am sending you the patch with relevant P4 publication from our project (www.liberouter.org).
I want to thank you for your consideration.
Best regards,
Pavel Benacek
> P4 Papers from Liberouter 

- _events/2018-08-20-tutorial.md
@jnfoster : I'll add more details as we firm things up.
> Tutorial Website

- _data/publications.yml
Adding publication details from SIGCOMM and IEEE-HPSR.
> Adding MACSAD publications from INTRIG group.

- _events/2018-09-24-p4-eu-workshop.md
@rkeverman : Can you please review?
> Added Xilinx and note about no-proceedings submissions.

- _events/2018-08-20-tutorial.md
@rkeverman , @jnfoster : can you please review?
> Added VM instructions to website

- _events/2018-09-24-p4-eu-workshop.md
- _pages/working-groups.md
@rkeverman : Can you please review? This PR adds the accepted papers, and removes the instructions on how to submit papers for review.
> Added accepted papers to website.

- _events/2018-09-24-p4-eu-workshop.md
@rkeverman : Here is one more to review. I've added the accepted posters and the venue address.
> Added posters and conference location.

- _events/2018-09-24-p4-eu-workshop.md
@rkeverman : I've now added accepted demos. Can you review one more time?
> Added demos

- _events/2018-09-24-p4-eu-workshop.md
@jnfoster , @rkeverman : can you please review? The authors of this paper would like the author order changed.
> Change author order at author's request.

- _data/publications.yml
Adding PVPP workshop paper from APNet and poster from SOSR
> Updating publication.yml to include PVPP

- _pages/specs.html
> Update link to P4Runtime specification

- _events/2019-03-29-de-hackathon.md
add third sponsor, economic hardship grant possibilities
> P4 hackathon europe update

- _events/2019-03-29-de-hackathon.md
add agenda
remove registration link
> updates to P4 Hackathon DE 2019

- _events/2019-05-01-p4-workshop.md
Adding abstract to first listed talk as a test
> Adding abstract

- _events/2019-05-01-p4-workshop.md
Adding Xilinx to the sponsorship section
> Updating sponsorship logos

- _events/2019-05-01-p4-workshop.md
Including accepted demos on the P4 Workshop webpage.
> Updated accepted demos

- _events/2019-05-01-p4-workshop.md
Only received 3 final talk abstracts so far.
> Updating final abstracts

- _events/2019-07-20-ietf105.md
@rkeverman : Can you take a look?
> Advertising the Montreal Hackathon.

- _events/2019-09-23-euro-p4-workshop.md
This is the webpage for the upcoming EuroP4 co-located with ANCS
> EuroP4 webpage

- _events/2019-09-23-euro-p4-workshop.md
Added Costin Raiciu as Keynote Speaker at EuroP4
> added Keynote EuroP4

- _events/2019-09-23-euro-p4-workshop.md
Delta Systems and Stordis: EuroP4
> 2 sponsors for EuroP4

- _events/2019-09-23-euro-p4-workshop.md
Adding Salvatore Signorello as web chair
> adding web chair

- _events/2019-09-23-euro-p4-workshop.md
> fixing stuff

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: added placeholder for Submission Instructions
> EuroP4: added placeholder for Submission Instructions

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: adding submission instruction
> EuroP4: adding submission instruction

- _events/2019-09-23-euro-p4-workshop.md
> added EuroP4 submission link

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: deadline extended by 3 days + some topic of interests
> extended deadline, + some topics

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: fixing some spacing for the logo
> fixing some spacing

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: date fixing + submission instructions for late submissions
> added late submission instructions

- _events/2019-09-23-euro-p4-workshop.md
> late submission link

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: agenda + posters/demos accepted
> EuroP4 preliminary agenda + posters and demos accepted

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: small fixes to the layout
> small fixes

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: small change to the program
> fix to the program

- _events/2019-09-23-euro-p4-workshop.md
> added CR instructions

- _events/2019-09-23-euro-p4-workshop.md
EuroP4: updating affiliation Mario Baldi
> updating affiliation

- _events/2019-09-23-euro-p4-workshop.md
> link to papers

- _pages/specs.html
See https://github.com/p4lang/p4runtime/issues/197
> Update P4Runtime spec links from AWS S3 to Github

- _pages/working-groups.md
I've been reviewing the P4.org website and noticed these affiliations are outdated. Will you review/confirm?
> Updating affiliations for Antonin and Robert

- _events/2020-p4-summit.md
Here's my first attempt to create the placeholder page for the P4 Summit 2020, which will be a combined 2-day event. How does it look?
> Create P4 Summit 2020 placeholder page

- _pages/specs.html
P4Runtime 1.1.0 was released on 02/03/2020.
> Update latest P4Runtime release from 1.0.0 to 1.1.0

- _drafts/2020-01-23-pensando-joins-p4.md
Take them or leave them, but here are few suggestions on rewording.
> Proposed edits to blog

- _drafts/2020-01-23-pensando-joins-p4.md
Made some changes to the names used for the Pensando card and other platform components. No changes otherwise to the content and language.
> Naming changes in 2020-01-23-pensando-joins-p4.md

- _events/2019-09-23-euro-p4-workshop.md
Fixing spaces on the EuroP4 page
> fixing spaces

- _events/2020-p4-summit.md
Reverts p4lang/p4lang.github.io#553
> Revert "Adding register button"

- _events/2020-p4-summit.md
Reverts p4lang/p4lang.github.io#563
> Revert "Finalize spacing on reg buttons"

- _pages/specs.html
INT 2.1 and Report 2.0 will be published within 1-2 days in Apps WG. Once approved, I will merged this PR in sync with Apps WG.
> Add INT spec links

- _pages/specs.html
P4Runtime 1.2.0 was released on 07/06/2020.
> Update latest P4Runtime release from 1.1.0 to 1.2.0

- _events/2020-12-01-euro-p4-workshop.md
Using the tentative date 2020-12-01, first day of CoNEXT
> Created website for EuroP4-2020

- _events/2020-12-01-euro-p4-workshop.md
Reverts p4lang/p4lang.github.io#598
> Revert "EuroP4 2020: Add an "Important dates" section "

- _events/2020-12-01-euro-p4-workshop.md
Finalize TPC list + minor formatting updates
> 3rd Europ4 2020: TPC update

- _posts/2020-10-23-geant-rare.md
Last edit to change blog date to current date.
> Changed blog date

- _events/2020-12-01-euro-p4-workshop.md
Added keynote title and abstract + credited the organizing team
> Europ4 2020 keynote

- _pages/specs.html
Depends on https://github.com/p4lang/p4runtime/pull/318
> Updating pointer to P4Runtime working draft

- _pages/working-groups.md
changed my login from moveright to alpinesnow. Will sign agreement next.
> changed mailing list and archive URLS

- _pages/tst.html
Nate - Would you check out my updates to the TST page? I tried keeping the layout the same. -rachel
> Updating TST members

- _pages/tst.html
Reverts p4lang/p4lang.github.io#641
> Revert "Updating TST members"
